### ISSUE TITLE
cadvisor: No targets visible in prometheus-ui 

### ISSUE THREAD

**Issue by tim-hilt** [ckotzbauer/helm-charts#143]
I did the following:

``` bash
kind create cluster
helm install monitoring prometheus-community/kube-prometheus-stack
helm install cadvisor ckotzbauer/cadvisor --set metrics.enabled=true
# 4. Wait for all pods to be running and healthy
# 5. Port forward prometheus-pod to localhost
# 6. Go to http://localhost:9090/targets?search=
```

but I didn't see any targets for cadvisor. Did I do something in the wrong order?

**Comment by ckotzbauer** [comment]
The order is correct, but you use the default configuration for both charts which are not compatible.

There's a label-selector to match installed servicemonitors. This selector `serviceMonitorSelector` (from the values.yaml of the `kube-prometheus-stack` chart) is set to `release: monitoring` in your case by default. (`monitoring` because you named your stack-installation that way). This means that all servicemonitors you install need a label `release: monitoring` to be detected by the prometheus-operator.

You have two options:
1. Set the `serviceMonitorSelectorNilUsesHelmValues` parameter from the `kube-prometheus-stack` to `false`, this will disable the default selection behaviour. All servicemonitors are detected now.
2. There needs to be a label at the cadvisor servicemonitor which matches the expected selector. Unfortunately there's no way to add custom-labels to the cadvisor servicemonitor right now, so a chart-update would be needed to achieve this.

**Comment by tim-hilt** [comment]
Thanks for the fast response and the helpful suggestions. Option 1 totally works for me. Thank you!
