### ISSUE TITLE
cadvisor: container_spec_cpu metrics not available

### ISSUE THREAD

**Issue by tim-hilt** [ckotzbauer/helm-charts#162]
Hi there! I noticed that metrics like `container_spec_cpu_quota` and `container_spec_cpu_period` are not provided when installing this helm-chart.

When searching for the issue online I found this: https://github.com/google/cadvisor/issues/3154 maybe it is related? OP said, that cadvisor doesn't construct the listed metrics, if

> cpu soft quota is enabled

but I don't know cadvisor well enough to see, whether this is the cause for the issue when using this helm-chart or how I could alter the current behavior. Any idea on your part?

**Comment by ckotzbauer** [comment]
Hi @tim-hilt,
I don't know that much about the internal behaviour of cadvisor. The behaviour seems to be different for different container-specs or kubelet-configs (see https://github.com/google/cadvisor/issues/3154#issuecomment-1463638119). Maybe there's something in your setup which was already mentioned. However, the behaviour is not triggered because you installed it via helm-chart.

**Comment by tim-hilt** [comment]
Hello @ckotzbauer and thanks for the reply. You're right in that this has to do with where I run the kubelet. In my case this would be on macOS in a kind-cluster. `cpuCFSquota` is a Linux-feature! That's why I couldn't use it on the Mac. No issue with the helm-chart, but rather with the OS. Closing.
